# Generated by Django 4.2.4 on 2023-09-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='descripton',
            new_name='description',
        ),
    ]
